### PR TITLE
Changed wording to be gender-neutral

### PR DESCRIPTION
**Pull request by jegtnes**
Hey @mfouquet, nice work on this manual. Just a quick amend here: Using the word "guy" as a general stand-in for "developer" or just "person" can be pretty exclusive to people who don't consider themselves as a _guy_. Replacing it with "person" doesn't make the wording sound any worse, but makes sure it doesn't exclude anyone.

### CODE REVIEW

**Comment by JodiWarren** [comment]
+1 good pull request

**Comment by mfouquet** [comment]
Agreed 100%. Merging.

**Comment by mfouquet** [comment]
Thanks for bringing this to my attention. Really appreciate it!

**Comment by jegtnes** [comment]
No worries! Thank you for merging. :heart:

**Pull request merged**
